### ISSUE TITLE
Issue in atom parsing regex in lisp/Parser.py

### ISSUE THREAD

**Issue by timmyjose** [andybelltree/Mary#2]
Issue: The atom parsing (exclusion) regex in lisp/parser.py is missing the left parenthesis ('(') character due to which the param list for a function definition (for instance) gets incorrectly parsed as part of the atom name and not as the start of a list.

![symbol-parsing-issue](https://user-images.githubusercontent.com/2051158/160844755-2a16ee9f-7eda-4961-8360-1b1f012ad06a.png)

Fix available in the following PR - https://github.com/andybelltree/Mary/pull/1

Screenshot with fix applied:
![symbol=parsing-issue-fix](https://user-images.githubusercontent.com/2051158/160845099-8742b70f-8d10-4f4c-a8e1-8f8b9149fc71.png)

Note: all tests passing with fix (`python runtests.py`).

**Comment by andybelltree** [comment]
Thanks! Good catch :)
